Repository team-moabam/moabam-FE, pull requests merged in 2023-12, with the labels that each got.

#404 feat: Push Notification 클릭 시 기존의 스크린 활용
  public/firebase-messaging-sw.js
  src/main.tsx
Labels: ☁️ FE, ✨ feature

#401 feat: 이벤트 페이지 수정 및 버튼 로직 추가
  src/Promotion/components/CouponButton.tsx
  src/Promotion/components/EventCard.tsx
  src/Promotion/components/EventList.tsx
  src/Promotion/coustants/couponToast.ts
  src/core/mocks/datas/coupons.ts
  src/core/mocks/handlers/coupons.ts
  src/core/types/Coupons.ts
  src/core/types/MyCoupon.ts
  src/core/types/index.ts
Labels: ☁️ FE, ✨ feature

#409 refactor: 루틴 수정 불가능하도록 주석 처리
  src/RoomSetting/hooks/useRoomForm.ts
  src/RoomSetting/tabs/RoomTab.tsx
  src/core/api/functions/roomAPI.ts
Labels: ☁️ FE, ♻️ refactor

#416 refactor: 방 수정시 방 상세로 페이지로 이동
  src/RoomSetting/hooks/useRoomForm.ts
Labels: ☁️ FE, ♻️ refactor

#421 fix: Firebase 앱 초기화 로직을 함수로 래핑
  src/core/utils/firebase.ts
  src/main.tsx
Labels: ☁️ FE, 🐛 fix

#412 refactor: 헤더의 뒤로가기가 갇히는 문제 수정
  src/pages/CouponPage.tsx
  src/pages/EventPage.tsx
  src/pages/MyBirdPage.tsx
  src/pages/OrderLogPage.tsx
  src/pages/ParticipateLogPage.tsx
  src/pages/RankPage.tsx
  src/pages/RoomLogPage.tsx
  src/pages/RoomNewPage.tsx
  src/pages/RoomSettingPage.tsx
  src/pages/StorePage.tsx
  src/pages/UserPage.tsx
  src/shared/Header/Header.stories.tsx
  src/shared/Header/components/Header.tsx
Labels: ☁️ FE, ♻️ refactor

#417 feat: 뱃지 구현 및 잔 버그들 수정
  public/assets/badge/birthOmok.png
  public/assets/badge/growOmok.png
  public/assets/badge/growOwl.png
  public/assets/badge/lock.png
  src/StoreList/components/StoreList.tsx
  src/UserProfile/components/UserMain.tsx
  src/core/mocks/datas/member.ts
Labels: ☁️ FE, ✨ feature

#425 fix: 방 상세 페이지 UI 플리커링 현상 제거
  src/RoomNavigate/components/RoomNavigate.tsx
  src/shared/Tab/components/TabBar.tsx
Labels: ☁️ FE, 🐛 fix

#420 feat: 쿠폰 발급 버튼 로직 수정
  src/Promotion/components/EventCard.tsx
  src/Promotion/components/EventList.tsx
  src/Promotion/utils/getDateDiff.ts
Labels: ☁️ FE, ✨ feature

#424 fix: 방 상세 공지 수정
  src/RoomDetail/components/RoomNotice.tsx
  src/core/mocks/datas/room.ts
Labels: ☁️ FE, 🐛 fix

#435 fix: 아무 방에도 참여하지 않을 시 Navigation 오류 수정
  src/RoomNavigate/components/RoomNavigate.tsx
  src/RoomNavigate/utils/pickRoom.ts
Labels: ☁️ FE, 🐛 fix

#437 fix: 변경된 isSignUp 필드 이름 대응
  src/core/api/functions/memberAPI.ts
  src/core/mocks/handlers/members.ts
  src/pages/JoinKakaoPage.tsx
Labels: ☁️ FE, 🐛 fix

#431 feat: 방 생성시 75% 설명 추가, 스크롤 바 변경
  src/App.tsx
  src/RoomNew/steps/SummaryStep.tsx
  src/core/styles/scrollbar.css
  src/main.css
Labels: ☁️ FE, ✨ feature

#438 fix : room detail, log 페이지 UI 수정
  src/RoomDetail/components/RoomDetailContainer.tsx
  src/RoomDetail/components/RoomHeader.tsx
  src/RoomDetail/components/RoomInfo.tsx
  src/RoomDetail/components/RoomMember.tsx
  src/RoomDetail/components/RoomMemberRank.tsx
  src/RoomDetail/components/RoomMembers.tsx
  src/RoomDetail/components/RoomSemi.tsx
  src/RoomDetail/components/RoomWorkspace.tsx
  src/RoomLog/components/RoomLogItem.tsx
  src/core/mocks/datas/room.ts
  src/core/types/Room.ts
  src/pages/RoomLogPage.tsx
  src/shared/Avatar/Avatar.stories.ts
  src/shared/Avatar/Avatar.tsx
  src/shared/Avatar/Profile.tsx
  src/shared/Icon/constants/icons.ts
Labels: ☁️ FE, 🐛 fix

#443 chore: theme_color 변경
  index.html
  vite.config.ts
Labels: ☁️ FE, 📦 chore

#444 fix: 인증 관련 시간 에러 수정
  src/RoomDetail/components/CertificationBottomSheet.tsx
  src/RoomDetail/components/RoomCalendarDate.tsx
  src/RoomDetail/components/RoomDetail.tsx
  src/RoomDetail/components/RoomDetailProvider.tsx
  src/RoomDetail/components/RoomMemberRank.tsx
  src/RoomDetail/components/RoomPreview.tsx
  src/RoomDetail/components/RoomPreviewRoutine.tsx
  src/RoomDetail/components/RoomRoutine.tsx
  src/RoomDetail/components/RoomWorkspace.tsx
  src/RoomDetail/utils/checkCertifyTime.ts
  src/core/mocks/datas/room.ts
  src/pages/RoomDetailPage.tsx
Labels: ☁️ FE, 🐛 fix

#446 feat: 방 상세 공지 및 방 배경 수정
  src/RoomDetail/components/RoomDetailContainer.tsx
  src/RoomDetail/components/RoomInfo.tsx
  src/RoomDetail/components/RoomMemberRank.tsx
  src/RoomDetail/components/RoomNotice.tsx
  src/RoomDetail/components/RoomSemi.tsx
  src/core/mocks/datas/room.ts
  src/core/utils/getTimeRange.ts
Labels: ☁️ FE, ✨ feature

#449 fix : 시간 인증 오류 수정
  src/RoomDetail/components/RoomPreviewRoutine.tsx
  src/RoomDetail/components/RoomRoutine.tsx
  src/RoomDetail/components/RoomWorkspace.tsx
  src/RoomDetail/utils/makeWeekCalendar.ts
  src/core/mocks/datas/room.ts
  src/core/mocks/handlers/rooms.ts
  src/pages/RoomDetailPage.tsx
Labels: ☁️ FE, 🐛 fix

#452 fix: 인증 버튼 에러 수정
  src/RoomDetail/components/RoomRoutine.tsx
Labels: ☁️ FE, 🐛 fix

#459 chore: 운영서버, 배포서버 환경변수 분기 처리
  .env.example
  .github/workflows/deploy_dev.yml
  .github/workflows/deploy_prod.yml
  src/core/api/instance.ts
  src/core/mocks/baseURL.ts
Labels: ☁️ FE, 📦 chore

#463 fix: 프로덕션 서버의 로그인 redirect 경로에 undefined 오류
  .github/workflows/pull_request.yml
  src/core/api/instance.ts
  src/core/constants/endpoints.ts
  src/core/mocks/baseURL.ts
  src/pages/JoinPage.tsx
Labels: ☁️ FE, 🐛 fix

#470 Feat/#464/edit rank badge store
  src/MyBird/components/ProductSheet.tsx
  src/RankList/components/RankLIst.tsx
  src/RankList/components/RankThumbnailItem.tsx
  src/StoreList/components/StoreList.tsx
  src/UserProfile/components/UserMain.tsx
  src/core/mocks/datas/member.ts
  src/pages/StorePage.tsx
Labels: ☁️ FE, ✨ feature

#474 feat: 뱃지 이미지 변경
  public/assets/badge/10.png
  public/assets/badge/50.png
  public/assets/badge/birth.png
  public/assets/badge/growOmok.png
  public/assets/badge/growOwl.png
  src/RankList/components/RankLIst.tsx
  src/UserProfile/components/UserMain.tsx
Labels: ☁️ FE, ✨ feature

#476 chore: Production 배포
  public/assets/badge/10.png
  public/assets/badge/50.png
  public/assets/badge/birth.png
  public/assets/badge/growOmok.png
  public/assets/badge/growOwl.png
  src/MyBird/components/ProductSheet.tsx
  src/RankList/components/RankLIst.tsx
  src/RankList/components/RankThumbnailItem.tsx
  src/RoomDetail/components/CertificationBottomSheet.tsx
  src/RoomDetail/components/CertificationProgress.tsx
  src/RoomDetail/components/RoomCalendar.tsx
  src/RoomDetail/components/RoomCalendarDate.tsx
  src/RoomDetail/components/RoomDetailImageInput.tsx
  src/RoomDetail/components/RoomHeader.tsx
  src/RoomDetail/components/RoomInfo.tsx
  src/RoomDetail/components/RoomRoutine.tsx
  src/RoomDetail/components/RoomSemi.tsx
  src/RoomDetail/components/RoomWorkspace.tsx
  src/RoomDetail/utils/makeTodayCertifyTime.ts
  src/RoomDetail/utils/makeWeekCalendar.ts
  src/StoreList/components/StoreList.tsx
  src/UserProfile/components/UserMain.tsx
  src/core/mocks/datas/member.ts
  src/core/mocks/datas/room.ts
  src/core/types/Room.ts
  src/pages/StorePage.tsx
Labels: ☁️ FE, 📦 chore

#478 fix: 프로덕션 배포에 결제 기능 임시 제한
  src/StoreList/components/StoreList.tsx
Labels: ☁️ FE, 🐛 fix

#479 fix: 프로덕션 배포에 결제 기능 임시 제한
  src/StoreList/components/StoreList.tsx
Labels: ☁️ FE, 📦 chore

#484 feat: PC view 버튼에 각종 페이지 링크 연결
  src/AboutMoabam/components/AboutMoabam.tsx
  src/AboutMoabam/components/BirdButton.tsx
Labels: ☁️ FE, ✨ feature

#485 feat: PC view 각종 버튼에 링크 연결
  src/AboutMoabam/components/AboutMoabam.tsx
  src/AboutMoabam/components/BirdButton.tsx
Labels: ☁️ FE, ✨ feature

#487 fix: 인증 성공 실패 여부 상태 보여주기
  src/RoomDetail/components/RoomRoutine.tsx
Labels: ☁️ FE, 🐛 fix

#482 feat: 닉네임 중복시 에러
  src/UserProfile/components/UserProfile.tsx
Labels: ☁️ FE, ✨ feature

#488 dev: dev를 main에 머지
  src/RoomDetail/components/RoomRoutine.tsx
  src/UserProfile/components/UserProfile.tsx
Labels: ☁️ FE, ✨ feature, 🐛 fix

#490 feat 유저에딧 트림처리
  src/UserProfile/components/UserProfile.tsx
  src/core/mocks/handlers/members.ts
Labels: ☁️ FE, ✨ feature

#493 2023-12-11 브랜치 정리 후 프로덕션 배포
  .env.example
  .github/workflows/deploy_dev.yml
  .github/workflows/deploy_prod.yml
  .github/workflows/pull_request.yml
  README.md
  public/assets/badge/10.png
  public/assets/badge/50.png
  public/assets/badge/birth.png
  public/assets/badge/growOmok.png
  public/assets/badge/growOwl.png
  src/AboutMoabam/components/AboutMoabam.tsx
  src/AboutMoabam/components/BirdButton.tsx
  src/LogList/components/LogList.tsx
  src/MyBird/components/BirdItem.tsx
  src/MyBird/components/MyBirdThumbnail.tsx
  src/MyBird/components/ProductSheet.tsx
  src/MyCoupon/components/MyCouponList.tsx
  src/OrderLogList/components/OrderLogList.tsx
  src/RankList/components/RankLIst.tsx
  src/RankList/components/RankThumbnailItem.tsx
  src/RoomDetail/components/CertificationBottomSheet.tsx
  src/RoomDetail/components/CertificationProgress.tsx
  src/RoomDetail/components/RoomCalendar.tsx
  src/RoomDetail/components/RoomCalendarDate.tsx
  src/RoomDetail/components/RoomDetailImageInput.tsx
  src/RoomDetail/components/RoomHeader.tsx
  src/RoomDetail/components/RoomInfo.tsx
  src/RoomDetail/components/RoomRoutine.tsx
  src/RoomDetail/components/RoomSemi.tsx
  src/RoomDetail/components/RoomWorkspace.tsx
  src/RoomDetail/utils/makeTodayCertifyTime.ts
  src/RoomDetail/utils/makeWeekCalendar.ts
  src/RoomSearch/components/SearchBar.tsx
  src/RoomSearch/hooks/useDebounceSearch.ts
  src/StoreList/components/StoreList.tsx
  src/UserEtc/components/UserEtc.tsx
  src/UserProfile/components/UserMain.tsx
  src/UserProfile/components/UserProfile.tsx
  src/core/api/instance.ts
  src/core/constants/endpoints.ts
  src/core/hooks/useDebounce.ts
  src/core/mocks/baseURL.ts
  src/core/mocks/datas/member.ts
  src/core/mocks/datas/room.ts
  src/core/mocks/handlers/members.ts
  src/core/types/Room.ts
  src/core/utils/debounce.ts
  src/main.tsx
  src/pages/JoinPage.tsx
  src/pages/StorePage.tsx
  src/setupWorker.ts
Labels: ☁️ FE
