Repository team-moabam/moabam-FE, pull requests merged in 2023-10, with the labels that each got.

#5 chore: 프로젝트 초기 환경설정
  .eslintignore
  .eslintrc.cjs
  .eslintrc.json
  .github/ISSUE_TEMPLATE/♻️-refactor.md
  .github/ISSUE_TEMPLATE/✨-feature.md
  .github/ISSUE_TEMPLATE/🚨-hotfix.md
  .github/pull_request_template.md
  .gitignore
  .husky/commit-msg
  .husky/pre-commit
  .prettierrc.json
  .vscode/settings.json
  commitlint.config.cjs
  package-lock.json
  package.json
  postcss.config.js
  src/App.css
  src/App.tsx
  src/assets/react.svg
  src/index.css
  src/main.css
  src/main.tsx
  src/routes/router.tsx
  tailwind.config.js
  tsconfig.json
  tsconfig.paths.json
  vite.config.ts
Labels: ☁️ FE, ⚙️ setting, 📦 chore

#7 chore: PR시 빌드하는 워크플로 작성
  .github/ISSUE_TEMPLATE/♻️-refactor.md
  .github/ISSUE_TEMPLATE/✨-feature.md
  .github/ISSUE_TEMPLATE/🚨-hotfix.md
  .github/workflows/pull_request.yml
  src/main.tsx
Labels: ☁️ FE

#8 chore: storybook 설치 및 설정
  .eslintrc.json
  .github/workflows/pull_request.yml
  .gitignore
  .storybook/main.ts
  .storybook/preview.ts
  README.md
  package-lock.json
  package.json
  src/stories/components/ExampleButton/ExampleButton.stories.tsx
  src/stories/components/ExampleButton/ExampleButton.tsx
  src/stories/components/ExampleHeader/ExampleHeader.stories.tsx
  src/stories/examples/Button.stories.ts
  src/stories/examples/Button.tsx
  src/stories/examples/Configure.mdx
  src/stories/examples/Header.stories.ts
  src/stories/examples/Header.tsx
  src/stories/examples/Page.stories.ts
  src/stories/examples/Page.tsx
  src/stories/examples/assets/accessibility.png
  src/stories/examples/assets/accessibility.svg
  src/stories/examples/assets/addon-library.png
  src/stories/examples/assets/assets.png
  src/stories/examples/assets/context.png
  src/stories/examples/assets/discord.svg
  src/stories/examples/assets/docs.png
  src/stories/examples/assets/figma-plugin.png
  src/stories/examples/assets/github.svg
  src/stories/examples/assets/share.png
  src/stories/examples/assets/styling.png
  src/stories/examples/assets/testing.png
  src/stories/examples/assets/theming.png
  src/stories/examples/assets/tutorials.svg
  src/stories/examples/assets/youtube.svg
  src/stories/examples/button.css
  src/stories/examples/header.css
  src/stories/examples/page.css
Labels: ☁️ FE, 📦 chore

#10 chore: 코드 스니펫 추가
  .gitignore
  .vscode/moabam.code-snippets
Labels: ☁️ FE, 📦 chore

#12 chore: 배포 CI 스크립트 작성
  .github/workflows/deploy.yml
  src/App.tsx
  src/main.tsx
  src/routes/router.tsx
Labels: ☁️ FE, 📦 chore

#14 chore: 디렉토리 구조 세팅
  .eslintrc.json
  package-lock.json
  package.json
  src/App.tsx
  src/core/api/functions/postTestAPI.ts
  src/core/api/instance.ts
  src/core/api/mutationHooks/.empty
  src/core/api/queries/index.ts
  src/core/api/queries/postsTest.ts
  src/core/api/queryHooks/.empty
  src/core/constants/.empty
  src/core/hooks/.empty
  src/core/routes/router.tsx
  src/core/store/.empty
  src/core/stories/components/ExampleButton/ExampleButton.stories.tsx
  src/core/stories/components/ExampleButton/ExampleButton.tsx
  src/core/stories/components/ExampleHeader/ExampleHeader.stories.tsx
  src/core/stories/examples/Button.stories.ts
  src/core/stories/examples/Button.tsx
  src/core/stories/examples/Configure.mdx
  src/core/stories/examples/Header.stories.ts
  src/core/stories/examples/Header.tsx
  src/core/stories/examples/Page.stories.ts
  src/core/stories/examples/Page.tsx
  src/core/stories/examples/assets/accessibility.png
  src/core/stories/examples/assets/accessibility.svg
  src/core/stories/examples/assets/addon-library.png
  src/core/stories/examples/assets/assets.png
  src/core/stories/examples/assets/context.png
  src/core/stories/examples/assets/discord.svg
  src/core/stories/examples/assets/docs.png
  src/core/stories/examples/assets/figma-plugin.png
  src/core/stories/examples/assets/github.svg
  src/core/stories/examples/assets/share.png
  src/core/stories/examples/assets/styling.png
  src/core/stories/examples/assets/testing.png
  src/core/stories/examples/assets/theming.png
  src/core/stories/examples/assets/tutorials.svg
  src/core/stories/examples/assets/youtube.svg
  src/core/stories/examples/button.css
  src/core/stories/examples/header.css
  src/core/stories/examples/page.css
  src/core/styles/.empty
  src/core/types/.empty
  src/core/utils/.empty
  src/pages/.empty
  src/shared/.empty
Labels: ☁️ FE, 📦 chore

#16 chore: MSW 설치 및 설정
  .env.example
  .gitignore
  package-lock.json
  package.json
  public/mockServiceWorker.js
  src/core/api/functions/examplePostAPI.ts
  src/core/api/instance.ts
  src/core/api/queries/examplePost.ts
  src/core/api/queries/index.ts
  src/core/api/queries/postsTest.ts
  src/core/mocks/baseURL.ts
  src/core/mocks/browser.ts
  src/core/mocks/datas/comments.ts
  src/core/mocks/datas/posts.ts
  src/core/mocks/handlers/exampleComments.ts
  src/core/mocks/handlers/examplePosts.ts
  src/core/mocks/handlers/index.ts
  src/main.tsx
Labels: ☁️ FE, 📦 chore

#19 chore: CI 스크립트에 백엔드 API 환경변수 추가
  .github/workflows/deploy.yml
Labels: ☁️ FE, 📦 chore

#22 chore: tailwind 색상 alias 설정
  .nvmrc
  tailwind.config.js
Labels: ☁️ FE, 📦 chore

#20 chore: Tailwind config 파일 작성
  src/core/examples/components/ExampleButton/ExampleButton.stories.tsx
  src/core/examples/components/ExampleButton/ExampleButton.tsx
  src/core/examples/components/ExampleHeader/ExampleHeader.stories.tsx
  src/core/examples/tailwind/TextExample.stories.tsx
  src/core/examples/tailwind/TextExample.tsx
  src/core/examples/tailwind/ThemeExample.stories.tsx
  src/core/examples/tailwind/ThemeExample.tsx
  src/core/routes/router.tsx
  src/core/stories/examples/Button.stories.ts
  src/core/stories/examples/Button.tsx
  src/core/stories/examples/Configure.mdx
  src/core/stories/examples/Header.stories.ts
  src/core/stories/examples/Header.tsx
  src/core/stories/examples/Page.stories.ts
  src/core/stories/examples/Page.tsx
  src/core/stories/examples/assets/accessibility.png
  src/core/stories/examples/assets/accessibility.svg
  src/core/stories/examples/assets/addon-library.png
  src/core/stories/examples/assets/assets.png
  src/core/stories/examples/assets/context.png
  src/core/stories/examples/assets/discord.svg
  src/core/stories/examples/assets/docs.png
  src/core/stories/examples/assets/figma-plugin.png
  src/core/stories/examples/assets/github.svg
  src/core/stories/examples/assets/share.png
  src/core/stories/examples/assets/styling.png
  src/core/stories/examples/assets/testing.png
  src/core/stories/examples/assets/theming.png
  src/core/stories/examples/assets/tutorials.svg
  src/core/stories/examples/assets/youtube.svg
  src/core/stories/examples/button.css
  src/core/stories/examples/header.css
  src/core/stories/examples/page.css
  src/main.css
Labels: ☁️ FE, 📦 chore

#31 feat: Button 관련 속성 정리
  .storybook/main.ts
  .vscode/settings.json
  package-lock.json
  package.json
  src/core/examples/tailwind/Button.stories.tsx
  src/core/styles/.empty
  src/core/styles/button.css
  src/main.css
  tailwind.config.js
Labels: ☁️ FE, ✨ feature

#43 feat: Icon 컴포넌트 작성
  src/shared/Icon/components/Icon.stories.tsx
  src/shared/Icon/components/Icon.tsx
  src/shared/Icon/constants/icons.ts
  src/shared/Icon/index.ts
Labels: ☁️ FE, ✨ feature

#46 feat: 페이지 레이아웃 작성
  src/App.tsx
  src/core/routes/router.tsx
  src/main.css
  src/main.tsx
Labels: ☁️ FE, ⚙️ setting
