Repository team-moabam/moabam-FE, pull requests merged in 2023-11, with the labels that each got.

#47 feat: Header 컴포넌트 작성
  src/shared/Header/Header.stories.tsx
  src/shared/Header/components/Header.tsx
  src/shared/Header/index.ts
Labels: ☁️ FE, ✨ feature

#50 feat: RoutineList 컴포넌트 작성
  src/shared/RoutineList/RoutineList.stories.tsx
  src/shared/RoutineList/components/RoutineItem.tsx
  src/shared/RoutineList/components/RoutineList.tsx
  src/shared/RoutineList/index.ts
Labels: ☁️ FE, ✨ feature

#42 feat: input component
  src/shared/Input/components/Input.stories.tsx
  src/shared/Input/components/Input.tsx
  src/shared/Input/components/PasswordInput.stories.tsx
  src/shared/Input/components/PasswordInput.tsx
  src/shared/Input/index.ts
Labels: ☁️ FE, ✨ feature

#40 feat: progressbar component
  src/shared/ProgressBar/components/ProgressBar.stories.tsx
  src/shared/ProgressBar/components/ProgressBar.tsx
  src/shared/ProgressBar/index.ts
Labels: ☁️ FE, ✨ feature

#53 feat: Accordion 컴포넌트 작성
  package-lock.json
  package.json
  src/shared/Accordion/Accordion.stories.tsx
  src/shared/Accordion/components/Accordion.tsx
  src/shared/Accordion/components/AccordionBody.tsx
  src/shared/Accordion/components/AccordionGroup.tsx
  src/shared/Accordion/components/AccordionHeader.tsx
  src/shared/Accordion/hooks/useAccordion.ts
  src/shared/Accordion/hooks/useAccordionGroup.ts
  src/shared/Accordion/index.ts
Labels: ☁️ FE, ✨ feature

#36 feat: Tab 컴포넌트 작성
  src/shared/Tab/Tab.stories.tsx
  src/shared/Tab/components/Tab.tsx
  src/shared/Tab/components/TabBar.tsx
  src/shared/Tab/components/TabHeader.tsx
  src/shared/Tab/components/TabItem.tsx
  src/shared/Tab/components/TabThumbnail.tsx
  src/shared/Tab/hooks/index.ts
  src/shared/Tab/hooks/useTab.ts
  src/shared/Tab/hooks/useTabBarStyle.ts
  src/shared/Tab/index.ts
  src/shared/Tab/utils/childrenToArray.ts
Labels: ☁️ FE, ✨ feature

#58 feat: ThemeContext 작성
  .storybook/preview-body.html
  index.html
  src/App.tsx
  src/core/constants/portals.ts
  src/core/hooks/useTheme.stories.tsx
  src/core/hooks/useTheme.tsx
  src/main.css
  src/main.tsx
Labels: ☁️ FE, ✨ feature

#54 feat: TimePicker 컴포넌트 작성
  .storybook/preview.ts
  package-lock.json
  package.json
  src/App.tsx
  src/TimePicker/components/TimePicker.stories.tsx
  src/TimePicker/components/TimePicker.tsx
  src/TimePicker/index.ts
  src/TimePicker/styles/TimePicker.css
Labels: ☁️ FE, ✨ feature

#35 feat: BottomSheet 컴포넌트 작성
  index.html
  src/core/examples/components/ExampleHeader/ExampleHeader.stories.tsx
  src/shared/BottomSheet/components/BottomSheet.stories.tsx
  src/shared/BottomSheet/components/BottomSheet.tsx
  src/shared/BottomSheet/hooks/useBottomSheet.ts
  src/shared/BottomSheet/index.ts
Labels: ☁️ FE, ✨ feature

#52 feat: Funnel 컴포넌트 및 훅 작성
  src/shared/Funnel/Funnel.stories.tsx
  src/shared/Funnel/components/Funnel.tsx
  src/shared/Funnel/components/Step.tsx
  src/shared/Funnel/hooks/useFunnel.tsx
  src/shared/Funnel/index.ts
  src/shared/Funnel/types/funnel.ts
Labels: ☁️ FE, ✨ feature

#38 feat: avatar 컴포넌트 생성
  .eslintrc.json
  public/icons/icon-crown.png
  src/shared/Avatar/Avatar.stories.ts
  src/shared/Avatar/Avatar.tsx
  src/shared/Avatar/Profile.tsx
  src/shared/Avatar/index.tsx
  tailwind.config.js
Labels: ☁️ FE, ✨ feature

#32 feat: Navbar 컴포넌트 작성
  src/shared/Navbar/components/Navbar.stories.tsx
  src/shared/Navbar/components/Navbar.tsx
  src/shared/Navbar/index.tsx
Labels: ☁️ FE, ✨ feature

#34 feat: Toast 컴포넌트 추가
  public/icons/icon-close-btn.png
  public/icons/icon-hand-cursor.png
  src/main.css
  src/shared/.empty
  src/shared/Toast/components/Toast.stories.tsx
  src/shared/Toast/components/Toast.tsx
  src/shared/Toast/components/useToast.stories.tsx
  src/shared/Toast/hooks/useToast.ts
  src/shared/Toast/index.ts
  tailwind.config.js
Labels: ☁️ FE, ✨ feature

#61 fix: tab style 버그 및 스토리북 수정
  src/shared/Tab/Tab.stories.tsx
  src/shared/Tab/components/Tab.tsx
Labels: ☁️ FE, 🐛 fix

#59 feat: 라우트 세팅 및 관련 커스텀훅 작성
  src/App.tsx
  src/core/hooks/.empty
  src/core/hooks/index.ts
  src/core/hooks/useMoveRoute.ts
  src/core/hooks/useRouteData.ts
  src/core/routes/index.ts
  src/core/routes/parameter.ts
  src/core/routes/router.tsx
  src/core/routes/routes.tsx
  src/pages/Room.tsx
Labels: ☁️ FE, ✨ feature

#64 feat: Navbar 컴포넌트 App 에 추가
  src/App.tsx
  src/core/routes/routes.tsx
  src/pages/.empty
  src/pages/Routines.tsx
  src/shared/Header/components/Header.tsx
  src/shared/Navbar/components/Navbar.tsx
  tailwind.config.js
Labels: ☁️ FE, ✨ feature

#66 feat: RoomNew 페이지 UI 작성
  public/assets/Omok.png
  public/assets/Owl.png
  src/RoomNew/components/BirdCard.tsx
  src/RoomNew/components/Navbar.tsx
  src/RoomNew/constants/styles.ts
  src/RoomNew/index.ts
  src/RoomNew/steps/BirdStep.tsx
  src/RoomNew/steps/PasswordStep.tsx
  src/RoomNew/steps/RoutineStep.tsx
  src/RoomNew/steps/SummaryStep.tsx
  src/RoomNew/steps/TimeStep.tsx
  src/core/routes/routes.tsx
  src/main.css
  src/pages/RoomNew.tsx
  src/shared/Funnel/hooks/useFunnel.tsx
  src/shared/Icon/index.ts
  tailwind.config.js
Labels: ☁️ FE, ✨ feature

#69 fix: Input 컴포넌트에 ref를 받지 못하는 문제 해결
  src/shared/Input/components/InnerTextInput.stories.tsx
  src/shared/Input/components/InnerTextInput.tsx
  src/shared/Input/components/Input.tsx
  src/shared/Input/components/PasswordInput.tsx
  src/shared/Input/index.ts
Labels: ☁️ FE, 🐛 fix

#73 feat: RoomNew 페이지의 스타일, 유효성 스키마 등 상수 정리
  src/RoomNew/constants/form.ts
  src/RoomNew/constants/literals.ts
  src/RoomNew/constants/styles.ts
  src/RoomNew/steps/RoutineStep/styles.ts
Labels: ☁️ FE, ✨ feature

#71 refactor: TimePicker props 이름 변경 및 formatHourString 함수 작성
  src/TimePicker/components/TimePicker.stories.tsx
  src/TimePicker/components/TimePicker.tsx
  src/TimePicker/utils/hour.ts
Labels: ☁️ FE, ♻️ refactor

#75 feat: RoomNew 페이지의 실제 로직 작성
  src/RoomNew/components/BirdCard.tsx
  src/RoomNew/components/Navbar.tsx
  src/RoomNew/constants/styles.ts
  src/RoomNew/steps/BirdStep.tsx
  src/RoomNew/steps/PasswordStep.tsx
  src/RoomNew/steps/RoutineStep.tsx
  src/RoomNew/steps/RoutineStep/MemberSection.tsx
  src/RoomNew/steps/RoutineStep/NameSection.tsx
  src/RoomNew/steps/RoutineStep/RoutineSection.tsx
  src/RoomNew/steps/RoutineStep/index.tsx
  src/RoomNew/steps/SummaryStep.tsx
  src/RoomNew/steps/TimeStep.tsx
  src/pages/RoomNew.tsx
Labels: ☁️ FE, ✨ feature

#83 Fix: Accordion 컴포넌트 디폴트 너비 및 커스텀 범위 수정
  src/shared/Accordion/Accordion.stories.tsx
  src/shared/Accordion/components/Accordion.tsx
  src/shared/Accordion/components/AccordionBody.tsx
  src/shared/Accordion/components/AccordionGroup.tsx
  src/shared/Accordion/components/AccordionHeader.tsx
  src/shared/Accordion/hooks/useAccordionGroup.ts
Labels: ☁️ FE, 🐛 fix

#86 fix: BottomSheet의 width 및 z-index 문제 수정
  src/App.tsx
  src/main.css
  src/shared/BottomSheet/components/BottomSheet.tsx
  tailwind.config.js
Labels: ☁️ FE, 🐛 fix

#78 Feat : Room page UI
  public/level1.png
  src/App.tsx
  src/RoomDetail/components/ImageList.tsx
  src/RoomDetail/components/RoomCalendar.tsx
  src/RoomDetail/components/RoomInfo.tsx
  src/RoomDetail/components/RoomMembers.tsx
  src/RoomDetail/components/RoomNotice.tsx
  src/RoomDetail/components/RoomProgress.tsx
  src/RoomDetail/components/RoomRoutine.tsx
  src/RoomDetail/components/RoomWorkspace.tsx
  src/core/routes/routes.tsx
  src/pages/RoomDetail.tsx
  src/shared/Icon/constants/icons.ts
  src/shared/ProgressBar/components/ProgressBar.tsx
  tailwind.config.js
Labels: ☁️ FE, ✨ feature

#82 Feat: RoomLogPageUI 추가
  src/RoomLog/components/RoomLogItem.tsx
  src/core/routes/routes.tsx
  src/pages/RoomLog.tsx
Labels: ☁️ FE, ✨ feature

#77 feat: axios instance 및 interceptor 작성
  src/core/api/functions/examplePostAPI.ts
  src/core/api/instance.ts
  src/core/api/types.ts
Labels: ☁️ FE, ✨ feature

#85 feat: header title prop 수정
  src/shared/Header/Header.stories.tsx
  src/shared/Header/components/Header.tsx
Labels: ☁️ FE, 🐛 fix

#88 feat: 방 생성 페이지의 요약 스텝 디자인 변경
  src/RoomNew/steps/SummaryStep.tsx
Labels: ☁️ FE, ✨ feature

#91 Refactor: tailwind merge라이브러리 적용
  package-lock.json
  package.json
  src/shared/Accordion/components/Accordion.tsx
  src/shared/Accordion/components/AccordionBody.tsx
  src/shared/Accordion/components/AccordionHeader.tsx
  src/shared/BottomSheet/components/BottomSheet.tsx
  src/shared/Header/components/Header.tsx
  src/shared/Icon/components/Icon.tsx
  src/shared/Input/components/InnerTextInput.tsx
  src/shared/Input/components/Input.tsx
  src/shared/ProgressBar/components/ProgressBar.tsx
  src/shared/RoutineList/components/RoutineList.tsx
  src/shared/Tab/components/Tab.tsx
Labels: ☁️ FE, ♻️ refactor

#98 feat: tanstack-query의 defaultError 설정
  package-lock.json
  package.json
  src/core/api/mutations/.empty
  src/core/api/options/examplePost.ts
  src/core/api/options/index.ts
  src/core/api/queries/.empty
  src/core/api/queries/examplePost.ts
  src/core/api/types.ts
Labels: ☁️ FE, ✨ feature

#94 feat: Room 목록 관련 컴포넌트 작성
  src/App.tsx
  src/RoomList/components/BugInfo.tsx
  src/RoomList/components/CertifyButton.tsx
  src/RoomList/components/RoomAccordion.tsx
  src/RoomList/components/RoomCard.tsx
  src/RoomList/hooks/useHover.ts
  src/RoomList/index.ts
  src/RoomList/mocks/myJoinRoom.ts
  src/RoomList/mocks/totalRooms.ts
  src/RoomList/mocks/types/myJoinRoom.d.ts
  src/RoomList/mocks/types/rooms.d.ts
  src/RoomList/styles/roomList.css
  src/RoomSummary/components/IconText.tsx
  src/RoomSummary/components/RoomSummary.tsx
  src/RoomSummary/index.ts
  src/core/hooks/useMoveRoute.ts
  src/core/routes/parameter.ts
  src/core/routes/routes.tsx
  src/main.css
  src/pages/Routines.tsx
  src/pages/Search.tsx
  src/shared/Accordion/components/AccordionHeader.tsx
  src/shared/Icon/constants/icons.ts
  src/shared/Tab/components/TabBar.tsx
  src/shared/Tab/hooks/useTabBarStyle.ts
Labels: ☁️ FE, ✨ feature

#99 feat: Routines 페이지 UI 작성
  src/RoomList/components/RoomAccordion.tsx
  src/RoomList/components/RoomCard.tsx
  src/RoomList/styles/roomListStyle.ts
  src/RoomSlide/components/BlankCard.tsx
  src/RoomSlide/components/RoomSlide.tsx
  src/RoomSlide/constants/dayType.ts
  src/RoomSlide/index.ts
  src/core/routes/routes.tsx
  src/pages/Routines.tsx
  src/pages/RoutinesPage.tsx
Labels: ☁️ FE, ✨ feature

#107 feat: prev prop 타입 RouteNames 로 수정
  src/pages/RoomLog.tsx
  src/pages/RoomNew.tsx
  src/shared/Header/Header.stories.tsx
  src/shared/Header/components/Header.tsx
Labels: ☁️ FE, ✨ feature

#109 feat: LoadingSpinner 컴포넌트 작성
  src/shared/LoadingSpinner/components/LoadingSpinner.stories.tsx
  src/shared/LoadingSpinner/components/LoadingSpinner.tsx
  src/shared/LoadingSpinner/index.ts
Labels: ☁️ FE, ✨ feature

#93 feat: 방 생성 API 호출 및 버튼 로딩 처리
  src/RoomNew/components/Navbar.tsx
  src/RoomNew/steps/RoutineStep/RoutineSection.tsx
  src/core/api/functions/roomAPI.ts
  src/core/api/types.ts
  src/core/mocks/handlers/index.ts
  src/core/mocks/handlers/rooms.ts
  src/pages/RoomNew.tsx
Labels: ☁️ FE, ✨ feature

#111 fix: 탭바 오류 수정
  src/shared/Tab/components/TabBar.tsx
Labels: ☁️ FE, 🐛 fix

#113 chore: 빌드 테스트 CI 속도 개선
  .github/workflows/pull_request.yml
Labels: ☁️ FE, 📦 chore

#100 feat: 방 상세 API 호출
  src/RoomDetail/components/CertificationProgress.tsx
  src/RoomDetail/components/ImageList.tsx
  src/RoomDetail/components/RoomCalendar.tsx
  src/RoomDetail/components/RoomInfo.tsx
  src/RoomDetail/components/RoomMemberRank.tsx
  src/RoomDetail/components/RoomMembers.tsx
  src/RoomDetail/components/RoomNotice.tsx
  src/RoomDetail/components/RoomRoutine.tsx
  src/RoomDetail/components/RoomWorkspace.tsx
  src/RoomLog/components/RoomLogItem.tsx
  src/core/api/functions/roomAPI.ts
  src/core/mocks/datas/room.ts
  src/core/mocks/handlers/rooms.ts
  src/core/routes/routes.tsx
  src/core/types/Image.ts
  src/core/types/Member.ts
  src/core/types/Room.ts
  src/pages/RoomDetailPage.tsx
  src/pages/RoomLogPage.tsx
  src/shared/Avatar/Avatar.tsx
  src/shared/Toast/components/Toast.tsx
  tailwind.config.js
Labels: ☁️ FE, ✨ feature

#114 feat: 방 관리 페이지 UI 작성
  src/RoomNew/components/Navbar.tsx
  src/RoomSetting/index.ts
  src/RoomSetting/tabs/MemberTab.tsx
  src/RoomSetting/tabs/RemoveTab.tsx
  src/RoomSetting/tabs/RoomTab.tsx
  src/core/routes/routes.tsx
  src/pages/RoomNewPage.tsx
  src/pages/RoomSettingPage.tsx
Labels: ☁️ FE, ✨ feature

#128 docs: readme 가볍게 정리
  README.md
Labels: ☁️ FE, 📝 docs

#125 feat: 방 관리 페이지 완성
  package-lock.json
  package.json
  src/RoomForm/components/Password.tsx
  src/RoomForm/components/Routines.tsx
  src/RoomForm/components/UserCount.tsx
  src/RoomForm/constants/literals.ts
  src/RoomForm/constants/styles.ts
  src/RoomForm/index.ts
  src/RoomNew/components/BirdCard.tsx
  src/RoomNew/components/Navbar.tsx
  src/RoomNew/constants/form.ts
  src/RoomNew/constants/literals.ts
  src/RoomNew/hooks/useRoomForm.ts
  src/RoomNew/index.ts
  src/RoomNew/steps/BirdStep.tsx
  src/RoomNew/steps/PasswordStep.tsx
  src/RoomNew/steps/RoutineStep.tsx
  src/RoomNew/steps/RoutineStep/NameSection.tsx
  src/RoomNew/steps/RoutineStep/RoutineSection.tsx
  src/RoomNew/steps/RoutineStep/index.tsx
  src/RoomNew/steps/RoutineStep/styles.ts
  src/RoomNew/steps/SummaryStep.tsx
  src/RoomNew/steps/TimeStep.tsx
  src/RoomSetting/components/LoadingFallback.tsx
  src/RoomSetting/hooks/useRoomForm.ts
  src/RoomSetting/index.ts
  src/RoomSetting/tabs/RoomTab.tsx
  src/core/api/functions/roomAPI.ts
  src/core/api/options/index.ts
  src/core/api/options/room.ts
  src/core/mocks/handlers/rooms.ts
  src/pages/RoomDetailPage.tsx
  src/pages/RoomNewPage.tsx
  src/pages/RoomSettingPage.tsx
Labels: ☁️ FE, ♻️ refactor, ✨ feature

#123 feat: 방 생성 페이지의 스텝 이동시 투명도 트랜지션 효과
  src/pages/RoomNewPage.tsx
Labels: ☁️ FE, ✨ feature

#129 feat: 시작페이지 UI 작성
  public/assets/Moon.png
  public/assets/MorningMountain.png
  public/assets/NightMountain.png
  public/assets/Sun.png
  public/assets/branch.png
  public/assets/skins/awakeOmokSkin1.png
  public/assets/skins/awakeOwlSkin1.png
  public/assets/skins/sleepOmokSkin1.png
  public/assets/skins/sleepOwlSkin1.png
  src/RoomList/components/RoomAccordion.tsx
  src/StartSlide/components/Background.tsx
  src/StartSlide/components/Star.tsx
  src/StartSlide/components/UserInfo.tsx
  src/StartSlide/constants/contents.ts
  src/StartSlide/index.ts
  src/StartSlide/mocks/userData.ts
  src/StartSlide/styles/star.css
  src/core/hooks/useHover.ts
  src/core/routes/routes.tsx
  src/pages/StartPage.tsx
  src/shared/Header/Header.stories.tsx
Labels: ☁️ FE, ✨ feature

#121 feat: 방 검색 페이지 UI 작성
  src/RoomList/components/RoomAccordion.tsx
  src/RoomSearch/components/ResultList.tsx
  src/RoomSearch/components/SearchBar.tsx
  src/RoomSearch/components/Selection.tsx
  src/RoomSearch/index.ts
  src/RoomSearch/types/search.d.ts
  src/core/routes/routes.tsx
  src/pages/Search.tsx
  src/pages/SearchPage.tsx
Labels: ☁️ FE, ✨ feature

#135 인풋 다크모드 적용
  src/shared/Input/components/Input.tsx
Labels: ☁️ FE, ♻️ refactor

#136 feat: 시작페이지 트랜지션 구현
  src/StartSlide/components/Background.tsx
  src/StartSlide/components/Star.tsx
  src/StartSlide/components/SwipeArrow.tsx
  src/StartSlide/components/UserBird.tsx
  src/StartSlide/components/UserInfo.tsx
  src/StartSlide/constants/contents.ts
  src/StartSlide/hooks/useRandomMessage.ts
  src/StartSlide/styles/swipeArrow.css
  src/StartSlide/utils/getRandomValue.ts
  src/pages/StartPage.tsx
  src/shared/Icon/constants/icons.ts
Labels: ☁️ FE, ✨ feature

#119 feat: 조인 페이지 정적 작성
  public/kakaoTalk.png
  src/core/routes/routes.tsx
  src/pages/JoinPage.tsx
Labels: ☁️ FE, ✨ feature

#118 feat: not found 페이지 작성
  public/notFound.png
  src/core/routes/routes.tsx
  src/pages/NotFoundPage.tsx
Labels: ☁️ FE, ✨ feature

#139 chore: 새 스킨 에셋 추가
  public/assets/skins/awakeOmokSkin0.png
  public/assets/skins/awakeOmokSkin2.png
  public/assets/skins/awakeOmokSkin3.png
  public/assets/skins/awakeOwlSkin0.png
  public/assets/skins/awakeOwlSkin2.png
  public/assets/skins/awakeOwlSkin3.png
  public/assets/skins/defaultOmok.png
  public/assets/skins/sleepOmokSkin0.png
  public/assets/skins/sleepOmokSkin2.png
  public/assets/skins/sleepOmokSkin3.png
  public/assets/skins/sleepOwlSkin0.png
  public/assets/skins/sleepOwlSkin2.png
  public/assets/skins/sleepOwlSkin3.png
Labels: ☁️ FE

#147 chore: PWA 기본 설정
  .gitignore
  index.html
  package-lock.json
  package.json
  public/apple-touch-icon-180x180.png
  public/favicon.ico
  public/logo.png
  public/maskable-icon-512x512.png
  public/pwa-192x192.png
  public/pwa-512x512.png
  public/pwa-64x64.png
  public/vite.svg
  pwa-assets.config.ts
  vite.config.ts
Labels: ☁️ FE, 📦 chore

#117 feat: 마이페이지 및 기타 페이지들 정적 작성
  public/assets/user.png
  src/LogList/components/LogList.tsx
  src/LogList/mocks/roomHistory.ts
  src/OrderLogList/components/OrderLogList.tsx
  src/OrderLogList/mocks/Bugs.ts
  src/OrderLogList/mocks/bugsHistory.ts
  src/OrderLogList/mocks/types/bugs.ts
  src/StoreList/components/StoreList.tsx
  src/StoreList/mocks/products.ts
  src/StoreList/mocks/types/product.ts
  src/UserBugs/components/UserBugs.tsx
  src/UserBugs/mocks/bugs.ts
  src/UserEtc/components/Logout.tsx
  src/UserEtc/components/UserEtc.tsx
  src/UserEtc/components/WithDrawal.tsx
  src/UserProfile/components/EditInput.tsx
  src/UserProfile/components/UserMain.tsx
  src/UserProfile/components/UserProfile.tsx
  src/UserProfile/mocks/userData.ts
  src/core/routes/routes.tsx
  src/pages/CouponPage.tsx
  src/pages/OrderLogPage.tsx
  src/pages/RankPage.tsx
  src/pages/StorePage.tsx
  src/pages/UserPage.tsx
  src/pages/VisitLogPage.tsx
  src/shared/ProgressBar/components/ProgressBar.tsx
Labels: ☁️ FE, ✨ feature

#142 feat: 루틴 사진 인증 로직
  src/RoomDetail/components/CertificationBottomSheet.tsx
  src/RoomDetail/components/ImageInput.tsx
  src/RoomDetail/components/ImageList.tsx
  src/RoomDetail/components/RoomRoutine.tsx
  src/RoomDetail/index.ts
  src/RoomDetail/types/type.ts
  src/core/types/Image.ts
  src/pages/RoomDetailPage.tsx
  src/shared/Navbar/components/Navbar.tsx
  tailwind.config.js
Labels: ☁️ FE, ✨ feature

#137 feat: 방 관리 기능 완성
  src/RoomSetting/tabs/MemberTab.tsx
  src/RoomSetting/tabs/MemberTab/DelegationButton.tsx
  src/RoomSetting/tabs/MemberTab/KickButton.tsx
  src/RoomSetting/tabs/MemberTab/index.tsx
  src/RoomSetting/tabs/MemberTab/styles.ts
  src/RoomSetting/tabs/RemoveTab.tsx
  src/core/api/functions/roomAPI.ts
  src/core/mocks/handlers/rooms.ts
  src/pages/RoomSettingPage.tsx
Labels: ☁️ FE, ✨ feature

#134 feat: 방 생성 및 방 관리 페이지 다크모드 대응
  src/RoomForm/components/Routines.tsx
  src/RoomForm/components/UserCount.tsx
  src/RoomForm/constants/styles.ts
  src/RoomNew/components/BirdCard.tsx
  src/RoomNew/components/Navbar.tsx
  src/RoomSetting/components/LoadingFallback.tsx
  src/RoomSetting/tabs/RoomTab.tsx
  src/TimePicker/components/TimePicker.tsx
  src/TimePicker/styles/TimePicker.css
  src/pages/RoomNewPage.tsx
Labels: ☁️ FE, ✨ feature

#144 Feat: 쿠폰 관련 페이지 작성
  src/Promotion/components/EventBanner.tsx
  src/Promotion/components/EventCard.tsx
  src/Promotion/index.ts
  src/Promotion/mocks/coupons.ts
  src/Promotion/mocks/types/couponType.ts
  src/RoomList/components/BugInfo.tsx
  src/RoomList/components/CertifyButton.tsx
  src/RoomSearch/components/Selection.tsx
  src/RoomSlide/components/RoomSlide.tsx
  src/RoomSlide/index.ts
  src/core/api/options/coupon.ts
  src/core/mocks/datas/coupons.ts
  src/core/mocks/handlers/coupons.ts
  src/core/routes/routes.tsx
  src/pages/EventPage.tsx
  src/pages/RoutinesPage.tsx
  src/pages/SearchPage.tsx
Labels: ☁️ FE, ✨ feature

#151 fix: statusCode 파싱 로직 제거
  src/core/api/instance.ts
  src/core/api/types.ts
Labels: ☁️ FE, 🐛 fix

#155 Refactor : 토스트 컴포넌트
  package-lock.json
  package.json
  src/shared/Toast/components/Toast.stories.tsx
  src/shared/Toast/components/Toast.tsx
  src/shared/Toast/components/ToastItem.tsx
  src/shared/Toast/components/ToastManager.tsx
  src/shared/Toast/components/useToast.stories.tsx
  src/shared/Toast/hooks/useTimeout.tsx
Labels: ☁️ FE, ♻️ refactor

#152 feat: 루틴 페이지 API 연결, Deffered 컴포넌트 구현
  src/Promotion/components/EventBanner.tsx
  src/RoomList/components/BugInfo.tsx
  src/RoomList/components/CertifyButton.tsx
  src/RoomList/components/RoomCard.tsx
  src/RoomList/mocks/myJoinRoom.ts
  src/RoomList/mocks/totalRooms.ts
  src/RoomList/mocks/types/rooms.ts
  src/RoomSlide/components/BlankCard.tsx
  src/RoomSlide/components/NewRoomCard.tsx
  src/RoomSlide/components/RoomData.tsx
  src/RoomSlide/components/RoomDataFallback.tsx
  src/RoomSlide/components/RoomSlide.tsx
  src/RoomSummary/components/RoomSummary.tsx
  src/core/api/functions/bugAPI.ts
  src/core/api/functions/couponAPI.ts
  src/core/api/functions/roomAPI.ts
  src/core/api/options/bug.ts
  src/core/api/options/coupon.ts
  src/core/api/options/index.ts
  src/core/api/options/room.ts
  src/core/mocks/datas/coupons.ts
  src/core/mocks/datas/myJoinRoom.ts
  src/core/mocks/datas/todayBugs.ts
  src/core/mocks/handlers/bugs.ts
  src/core/mocks/handlers/coupons.ts
  src/core/mocks/handlers/index.ts
  src/core/mocks/handlers/rooms.ts
  src/core/types/Coupons.ts
  src/core/types/MyJoinRoom.ts
  src/core/types/Room.ts
  src/core/types/TodayBugs.ts
  src/core/types/index.ts
  src/pages/RoutinesPage.tsx
  src/shared/Deffered/components/Deffered.tsx
  src/shared/Deffered/index.ts
Labels: ☁️ FE, ✨ feature

#159 fix: 서비스 워커 관련 이슈 해결
  public/firebase-messaging-sw.js
  public/pwa/apple-touch-icon-180x180.png
  public/pwa/maskable-icon-512x512.png
  public/pwa/pwa-192x192.png
  public/pwa/pwa-512x512.png
  public/pwa/pwa-64x64.png
  vite.config.ts
Labels: ☁️ FE, 🐛 fix

#164 feat: 전체 방 조회 API 연결 및 기능 구현
  src/RoomSearch/components/ResultList.tsx
  src/RoomSearch/components/ResultListFallback.tsx
  src/RoomSearch/hooks/useIntersectionObserver.ts
  src/core/api/functions/couponAPI.ts
  src/core/api/functions/roomAPI.ts
  src/core/api/options/coupon.ts
  src/core/api/options/room.ts
  src/core/api/queries/index.ts
  src/core/api/queries/useInfiniteSearch.ts
  src/core/mocks/datas/totalRooms.ts
  src/core/mocks/handlers/rooms.ts
  src/core/types/TotalRooms.ts
  src/core/types/index.ts
  src/pages/SearchPage.tsx
Labels: ☁️ FE, ✨ feature

#163 feat: QueryErrorBoundary 컴포넌트 작성
  public/assets/PageError.png
  public/assets/UnknownError.png
  src/App.tsx
  src/main.tsx
  src/pages/RoomSettingPage.tsx
  src/shared/ErrorBoundary/components/NetworkFallback.tsx
  src/shared/ErrorBoundary/components/QueryErrorBoundary.tsx
  src/shared/ErrorBoundary/components/UnknownFallback.tsx
  src/shared/ErrorBoundary/index.ts
Labels: ☁️ FE, ✨ feature

#165 feat: 로그인 기능 구현
  .env.example
  package-lock.json
  package.json
  src/core/api/functions/memberAPI.ts
  src/core/mocks/handlers/index.ts
  src/core/mocks/handlers/members.ts
  src/core/routes/routes.tsx
  src/pages/JoinKakaoPage.tsx
  src/pages/JoinPage.tsx
Labels: ☁️ FE, ✨ feature

#172 chore: 배포시 env 내용 추가
  .github/workflows/deploy.yml
Labels: ☁️ FE, 📦 chore

#177 chore: 배포 S3 버킷 이름 변경
  .github/workflows/deploy.yml
Labels: ☁️ FE, 📦 chore

#180 fix: withCredentials 추가
  src/core/api/instance.ts
Labels: ☁️ FE, 🐛 fix

#149 refactor: 유저 로그 경로 수정
  src/UserEtc/components/UserEtc.tsx
  src/core/routes/routes.tsx
  src/pages/ParticipateLog.tsx
  src/pages/UserPage.tsx
Labels: ☁️ FE, ♻️ refactor

#169 feat: 방 관리, 방 생성 페이지 TODO 코드 구현
  src/RoomNew/components/Navbar.tsx
  src/RoomNew/hooks/useRoomForm.ts
  src/RoomNew/steps/BirdStep.tsx
  src/RoomNew/steps/SummaryStep.tsx
  src/RoomNew/steps/TimeStep.tsx
  src/RoomSetting/hooks/useRoomForm.ts
  src/RoomSetting/tabs/MemberTab/DelegationButton.tsx
  src/RoomSetting/tabs/MemberTab/KickButton.tsx
  src/RoomSetting/tabs/MemberTab/index.tsx
  src/RoomSetting/tabs/RemoveTab.tsx
  src/RoomSetting/tabs/RoomTab.tsx
  src/core/api/functions/roomAPI.ts
  src/core/api/options/room.ts
  src/core/mocks/datas/room.ts
  src/core/mocks/handlers/rooms.ts
  src/core/types/Room.ts
  src/pages/RoomDetailPage.tsx
  src/shared/Toast/components/ToastManager.tsx
Labels: ☁️ FE, ✨ feature

#181 feat: 시간 요청 및 테마 자동 변경 구현
  src/App.tsx
  src/core/api/functions/timeAPI.ts
  src/core/api/options/time.ts
  src/core/mocks/handlers/index.ts
  src/core/mocks/handlers/time.ts
  src/core/utils/getTimeRange.ts
Labels: ☁️ FE, ✨ feature

#185 feat: 아코디언 컴포넌트 수정
  src/RoomList/components/RoomAccordion.tsx
  src/RoomSearch/components/ResultList.tsx
  src/RoomSearch/components/Selection.tsx
  src/RoomSearch/types/search.d.ts
  src/shared/Accordion/components/Accordion.tsx
  src/shared/Accordion/components/AccordionBody.tsx
  src/shared/Accordion/components/AccordionGroup.tsx
  src/shared/Accordion/components/AccordionHeader.tsx
  src/shared/Accordion/hooks/useAccordion.ts
  src/shared/Accordion/hooks/useAccordionGroup.ts
Labels: ☁️ FE, ✨ feature

#191 feat: 로그인 시 멤버 ID를 로컬 스토리지에 저장하는 로직
  src/RoomNew/components/BirdCard.tsx
  src/RoomNew/components/Navbar.tsx
  src/RoomNew/hooks/useRoomForm.ts
  src/core/api/functions/roomAPI.ts
  src/core/constants/storageKeys.ts
  src/core/hooks/index.ts
  src/core/hooks/useLocalStorage.ts
  src/core/hooks/useTheme.tsx
  src/core/mocks/handlers/rooms.ts
  src/pages/JoinKakaoPage.tsx
Labels: ☁️ FE, ✨ feature

#198 feat: 로그인 관련 리다이렉션 로직 작성
  src/App.tsx
  src/core/api/functions/memberAPI.ts
  src/core/api/options/member.ts
  src/core/api/queryClient.ts
  src/core/api/types.ts
  src/core/mocks/handlers/members.ts
  src/main.tsx
  src/shared/ErrorBoundary/components/NetworkFallback.tsx
  src/shared/ErrorBoundary/components/UnknownFallback.tsx
  src/useCheckAuthRequired.ts
Labels: ☁️ FE, ✨ feature

#196 feat: 가이드 페이지 구현
  public/assets/guide/guideOmok.png
  public/assets/guide/guideRoutine.png
  src/Guide/components/GuideContent.tsx
  src/Guide/constants/guideContents.ts
  src/Guide/index.ts
  src/Guide/styles/swiperBullets.css
  src/core/routes/routes.tsx
  src/pages/GuidePage.tsx
Labels: ☁️ FE, ✨ feature

#200 fix: "undefined" is not valid JSON 이슈
  src/core/api/functions/memberAPI.ts
  src/core/api/queryClient.ts
  src/core/hooks/useLocalStorage.ts
  src/core/mocks/handlers/members.ts
  src/pages/JoinKakaoPage.tsx
Labels: ☁️ FE, 🐛 fix

#183 feat: FCM 토큰 발급 기능 작성
  .env.example
  .github/workflows/deploy.yml
  README.md
  package-lock.json
  package.json
  public/firebase-messaging-sw.js
  src/core/api/functions/notificationAPI.ts
  src/core/mocks/handlers/index.ts
  src/core/mocks/handlers/notifications.ts
  src/core/utils/debounce.ts
  src/core/utils/firebase.ts
  src/main.tsx
  src/pages/JoinKakaoPage.tsx
Labels: ☁️ FE, 📦 chore

#194 feat: 쿠폰 배너 수정 및 이벤트 페이지 완성
  public/assets/coupons/event_discount.png
  public/assets/coupons/event_gold.png
  public/assets/coupons/event_morning.png
  public/assets/coupons/event_night.png
  src/Promotion/components/DisabledCover.tsx
  src/Promotion/components/EventBanner.tsx
  src/Promotion/components/EventCard.tsx
  src/Promotion/components/EventCardFallback.tsx
  src/Promotion/components/EventList.tsx
  src/Promotion/components/EventListFallback.tsx
  src/Promotion/coustants/couponInfo.ts
  src/Promotion/index.ts
  src/Promotion/utils/getDateDiff.ts
  src/core/api/functions/couponAPI.ts
  src/core/api/options/coupon.ts
  src/core/mocks/datas/coupons.ts
  src/core/mocks/handlers/coupons.ts
  src/core/types/Coupons.ts
  src/pages/EventPage.tsx
  src/pages/Room.tsx
  src/pages/RoutinesPage.tsx
Labels: ☁️ FE, ✨ feature

#203 fix: 배포 CI 스크립트에 .env 가 잘못 입력된 부분 수정
  .github/workflows/deploy.yml
Labels: ☁️ FE, 🐛 fix

#205 fix: VITE_FIREBASE_API_KEY 추가
  .github/workflows/deploy.yml
Labels: ☁️ FE, 🐛 fix

#206 fix: 루틴페이지 bug api 호출 오류 수정
  src/RoomSlide/components/RoomData.tsx
  src/core/api/functions/bugAPI.ts
  src/core/api/options/bug.ts
  src/core/mocks/datas/todayBugs.ts
  src/core/mocks/handlers/bugs.ts
  src/core/types/TodayBugs.ts
  src/core/types/index.ts
Labels: ✨ feature, 🐛 fix

#208 fix: 방 전체 조회 및 검색 페이지 오류 수정
  src/RoomSlide/components/RoomSlide.tsx
  src/core/api/functions/roomAPI.ts
  src/core/api/queries/useSearchRooms.ts
  src/pages/SearchPage.tsx
Labels: ✨ feature, 🐛 fix

#211 fix: 방 전체 조회 및 검색 기능 요청 params 수정
  src/RoomSearch/components/Selection.tsx
  src/core/api/functions/roomAPI.ts
  src/core/api/queries/useSearchRooms.ts
  src/core/types/TotalRooms.ts
  src/pages/SearchPage.tsx
Labels: ☁️ FE, 🐛 fix

#212 fix: 검색 페이지 api response 타입 수정
  src/RoomList/components/RoomAccordion.tsx
  src/RoomList/mocks/totalRooms.ts
  src/RoomList/mocks/types/myJoinRoom.d.ts
  src/RoomList/mocks/types/rooms.ts
  src/core/mocks/datas/searchRooms.ts
  src/core/mocks/datas/totalRooms.ts
  src/core/mocks/handlers/rooms.ts
  src/core/types/TotalRooms.ts
Labels: ☁️ FE, 🐛 fix

#216 fix: FCM 토큰 API 호출 오류 수정
  src/core/api/functions/notificationAPI.ts
Labels: ☁️ FE, 🐛 fix

#173 feat: 캘린더 구현
  src/RoomDetail/components/RoomCalendar.tsx
  src/RoomDetail/components/RoomDetailContainer.tsx
  src/RoomDetail/components/RoomDetailProvider.tsx
  src/RoomDetail/components/RoomInfo.tsx
  src/RoomDetail/components/RoomWorkspace.tsx
  src/RoomDetail/constants/constant.ts
  src/RoomDetail/utils/utils.ts
  src/core/api/functions/roomAPI.ts
  src/core/mocks/datas/room.ts
  src/core/mocks/handlers/rooms.ts
  src/pages/RoomDetailPage.tsx
Labels: ☁️ FE, ✨ feature

#193 feat: 콕찌르기 기능
  src/RoomDetail/components/RoomMembers.tsx
  src/core/api/functions/roomAPI.ts
  src/core/mocks/datas/room.ts
  src/core/mocks/handlers/rooms.ts
  src/core/types/Member.ts
Labels: ☁️ FE, ✨ feature

#220 feat: 검색 시 해당되는 루틴목록 아코디언 펼쳐지게 수정
  src/RoomList/components/RoomAccordion.tsx
  src/shared/Accordion/components/Accordion.tsx
Labels: ☁️ FE, ✨ feature

#231 feat: 공유 버튼 기능 추가
  src/pages/RoomDetailPage.tsx
Labels: ☁️ FE, ✨ feature

#235 feat: PWA 설치 배너 추가
  .storybook/preview-body.html
  public/logo-dark.svg
  public/logo-light.svg
  public/logo.png
  pwa-assets.config.ts
  src/PWAInstallBanner/components/PWAInstallBanner.tsx
  src/PWAInstallBanner/index.ts
  src/pages/RoutinesPage.tsx
  src/shared/Icon/constants/icons.ts
  tailwind.config.js
Labels: ☁️ FE, ✨ feature

#229 feat: 방 세부정보 페이지로 이동하는 로직 구현
  src/App.tsx
  src/RoomNavigate/components/NoRoom.tsx
  src/RoomNavigate/components/RoomNavigate.tsx
  src/RoomNavigate/components/RoomNavigateFallback.tsx
  src/RoomNavigate/utils/pickRoomToShow.ts
  src/core/hooks/useMoveRoute.ts
  src/core/mocks/datas/myJoinRoom.ts
  src/core/utils/getTimeRange.ts
  src/pages/EventPage.tsx
  src/pages/Room.tsx
  src/pages/RoomNewPage.tsx
Labels: ☁️ FE, ✨ feature

#237 feat: 검색 페이지 아코디언 수정
  src/RoomList/components/RoomAccordion.tsx
  src/core/mocks/datas/searchRooms.ts
  src/shared/Accordion/components/AccordionBody.tsx
  src/shared/Accordion/components/AccordionHeader.tsx
Labels: ☁️ FE, ✨ feature

#241 fix: navigate 도중 발생한 오류 수정
  src/RoomNavigate/components/RoomNavigate.tsx
Labels: ☁️ FE, 🐛 fix

#225 fix: 배포 환경에서 로그인 리다이렉션이 불안정한 문제
  src/core/api/queryClient.ts
Labels: ☁️ FE, 🐛 fix

#236 feat: 신고 기능 구현
  src/RoomDetail/components/ReportBottomSheet.tsx
  src/RoomDetail/components/RoomInfo.tsx
  src/RoomDetail/components/RoomMembers.tsx
  src/RoomDetail/components/RoomWorkspace.tsx
  src/RoomDetail/constants/constant.ts
  src/RoomDetail/types/type.ts
  src/core/api/functions/notificationAPI.ts
  src/core/api/functions/reportAPI.ts
  src/core/mocks/handlers/index.ts
  src/core/mocks/handlers/notifications.ts
  src/core/mocks/handlers/reports.ts
  src/core/mocks/handlers/rooms.ts
  src/core/types/Reports.ts
  src/core/types/index.ts
Labels: ☁️ FE, ✨ feature

#245 feat : 인증 사진 기록 페이지
  src/RoomDetail/components/CertificationProgress.tsx
  src/RoomDetail/components/RoomCalendar.tsx
  src/RoomDetail/components/RoomCalendarDate.tsx
  src/RoomDetail/components/RoomWorkspace.tsx
  src/RoomLog/components/RoomLogItem.tsx
  src/core/mocks/datas/room.ts
  src/pages/RoomLogPage.tsx
  src/shared/Avatar/Avatar.tsx
Labels: ☁️ FE, ✨ feature

#242 feat: 마이페이지 및 기타 페이지 작성 및 기능구현
  src/LogList/components/LogList.tsx
  src/LogList/components/LogListFallback.tsx
  src/MyCoupon/components/MyCouponList.tsx
  src/MyCoupon/components/MyCouponListFallback.tsx
  src/OrderLogList/components/OrderLogList.tsx
  src/OrderLogList/components/OrderLogListFallback.tsx
  src/UserEtc/components/Logout.tsx
  src/UserEtc/components/UserEtc.tsx
  src/UserEtc/components/WithDrawal.tsx
  src/UserProfile/components/EditInput.tsx
  src/UserProfile/components/UserMain.tsx
  src/UserProfile/components/UserMainFallback.tsx
  src/UserProfile/components/UserProfile.tsx
  src/UserProfile/mocks/userData.ts
  src/core/api/functions/bugAPI.ts
  src/core/api/functions/couponAPI.ts
  src/core/api/functions/memberAPI.ts
  src/core/api/functions/roomAPI.ts
  src/core/api/options/bug.ts
  src/core/api/options/coupon.ts
  src/core/api/options/member.ts
  src/core/api/options/room.ts
  src/core/mocks/datas/bugHistory.ts
  src/core/mocks/datas/member.ts
  src/core/mocks/datas/myBug.ts
  src/core/mocks/datas/myCoupon.ts
  src/core/mocks/datas/participateHistory.ts
  src/core/mocks/handlers/bugs.ts
  src/core/mocks/handlers/coupons.ts
  src/core/mocks/handlers/members.ts
  src/core/mocks/handlers/rooms.ts
  src/core/routes/routes.tsx
  src/core/types/BugHistory.ts
  src/core/types/Member.ts
  src/core/types/MyBug.ts
  src/core/types/MyCoupon.ts
  src/core/types/ParticipateHistory.ts
  src/core/types/index.ts
  src/pages/CouponPage.tsx
  src/pages/NotFoundPage.tsx
  src/pages/OrderLogPage.tsx
  src/pages/ParticipateLogPage.tsx
  src/pages/UserPage.tsx
Labels: ☁️ FE, ✨ feature

#246 feat: 방 생성 페이지 접근 제한 및 로그인 리다이렉션 리팩토링
  src/PWAInstallBanner/components/PWAInstallBanner.tsx
  src/RoomNew/components/Navbar.tsx
  src/core/api/queryClient.ts
  src/pages/RoomNewPage.tsx
  src/useCheckAuthRequired.ts
Labels: ☁️ FE, ♻️ refactor, ✨ feature

#250 fix: 로그인 리다이렉션에 error.code 체크 로직 제거
  src/core/api/queryClient.ts
Labels: ☁️ FE, 🐛 fix

#218 feat: 탭 컴포넌트 기능 보완
  src/shared/Tab/components/Tab.tsx
  src/shared/Tab/components/TabItem.tsx
  src/shared/Tab/hooks/useTab.ts
Labels: ☁️ FE, ✨ feature

#251 feat: 루틴 페이지 슬라이드 UI 개선
  src/Promotion/components/EventBanner.tsx
  src/RoomSlide/components/DayInfo.tsx
  src/RoomSlide/components/RoomSlide.tsx
  src/RoomSlide/components/SlideController.tsx
  src/RoomSlide/hooks/useDayTypes.ts
  src/RoomSlide/index.ts
  src/pages/RoutinesPage.tsx
  tailwind.config.js
Labels: ☁️ FE, ✨ feature

#254 fix: PWA 배너가 리렌더링시 사라지는 오류 수정
  src/PWAInstallBanner/components/PWAInstallBanner.tsx
  src/PWAInstallBanner/hooks/usePWAInstallBanner.tsx
  src/main.tsx
Labels: ☁️ FE, ♻️ refactor, 🐛 fix

#248 refactor: 스토리북 정리
  .storybook/main.ts
  package-lock.json
  package.json
  src/TimePicker/components/TimePicker.stories.tsx
  src/core/examples/components/ExampleButton/ExampleButton.stories.tsx
  src/core/examples/components/ExampleButton/ExampleButton.tsx
  src/core/examples/components/ExampleHeader/ExampleHeader.stories.tsx
  src/core/examples/tailwind/TextExample.stories.tsx
  src/core/examples/tailwind/TextExample.tsx
  src/core/examples/tailwind/ThemeExample.stories.tsx
  src/core/examples/tailwind/ThemeExample.tsx
  src/core/styles/Button.stories.tsx
  src/shared/Avatar/Avatar.stories.ts
  src/shared/Icon/components/Icon.stories.tsx
  src/shared/Input/components/InnerTextInput.stories.tsx
  src/shared/Input/components/Input.stories.tsx
  src/shared/Input/components/PasswordInput.stories.tsx
  src/shared/Navbar/components/Navbar.stories.tsx
  src/shared/ProgressBar/components/ProgressBar.stories.tsx
Labels: ☁️ FE, ♻️ refactor

#258 feat: 루틴페이지 슬라이더 버튼 수정
  src/RoomSlide/components/SlideController.tsx
  src/pages/RoutinesPage.tsx
Labels: ☁️ FE, ✨ feature

#260 feat: 모바일 브라우저 UI 문제 해결
  index.html
  src/main.css
Labels: ☁️ FE, 🐛 fix

#262 refactor: 스토리 북 MDX, decorator 활용해서 정리
  src/core/hooks/useTheme.mdx
  src/core/hooks/useTheme.stories.tsx
  src/shared/Funnel/Funnel.mdx
  src/shared/Funnel/Funnel.stories.tsx
  src/shared/Icon/components/Icon.stories.tsx
Labels: ☁️ FE, ♻️ refactor

#268 fix: 랭크, 조인, 404 높이 수정
  src/pages/JoinPage.tsx
  src/pages/NotFoundPage.tsx
  src/pages/RankPage.tsx
Labels: ☁️ FE, 🐛 fix

#269 refactor: 상세페이지에 서버타임 적용
  src/RoomDetail/components/CertificationBottomSheet.tsx
  src/RoomDetail/components/CertificationProgress.tsx
  src/RoomDetail/components/ImageInput.tsx
  src/RoomDetail/components/ReportBottomSheet.tsx
  src/RoomDetail/components/RoomCalendar.tsx
  src/RoomDetail/components/RoomCalendarDate.tsx
  src/RoomDetail/components/RoomDetailContainer.tsx
  src/RoomDetail/components/RoomDetailFallback.tsx
  src/RoomDetail/components/RoomDetailProvider.tsx
  src/RoomDetail/components/RoomHeader.tsx
  src/RoomDetail/components/RoomInfo.tsx
  src/RoomDetail/components/RoomMemberRank.tsx
  src/RoomDetail/components/RoomMembers.tsx
  src/RoomDetail/components/RoomRoutine.tsx
  src/RoomDetail/components/RoomWorkspace.tsx
  src/RoomDetail/constants/constant.ts
  src/RoomDetail/utils/checkCertifyTime.ts
  src/RoomDetail/utils/isMorning.ts
  src/RoomDetail/utils/makeTodayCertifyTime.ts
  src/RoomDetail/utils/makeWeekCalendar.ts
  src/pages/RoomDetailPage.tsx
Labels: ☁️ FE, ♻️ refactor

#184 feat: 상점(스킨페이지) 작성
  public/assets/morningShop.png
  public/assets/nightShop.png
  src/MyBird/components/BirdItem.tsx
  src/MyBird/components/BirdItems.tsx
  src/MyBird/components/HeaderWallet.tsx
  src/MyBird/components/MyBirdProvider.tsx
  src/MyBird/components/MyBirdThumbnail.tsx
  src/MyBird/components/ProductSheet.tsx
  src/UserProfile/components/UserMain.tsx
  src/core/api/functions/itemAPI.ts
  src/core/api/options/item.ts
  src/core/hooks/useDebounce.ts
  src/core/mocks/datas/item.ts
  src/core/mocks/handlers/index.ts
  src/core/mocks/handlers/item.ts
  src/core/routes/routes.tsx
  src/core/types/index.ts
  src/core/types/item.ts
  src/pages/MyBirdPage.tsx
Labels: ☁️ FE, ✨ feature

#255 feat: 시작 페이지 API 연결 및 로딩 처리
  src/StartSlide/components/Background.tsx
  src/StartSlide/components/SwipeArrow.tsx
  src/StartSlide/components/UserBird.tsx
  src/StartSlide/components/UserInfo.tsx
  src/StartSlide/components/UserInfoFallback.tsx
  src/StartSlide/constants/contents.ts
  src/StartSlide/index.ts
  src/core/mocks/datas/member.ts
  src/pages/StartPage.tsx
Labels: ☁️ FE, ✨ feature

#272 feat: 상점 (결제)
  package-lock.json
  package.json
  public/assets/payment/fail.png
  public/assets/payment/success.png
  src/MyCoupon/components/MyCouponList.tsx
  src/StoreList/components/StoreList.tsx
  src/core/api/functions/bugAPI.ts
  src/core/api/functions/couponAPI.ts
  src/core/api/functions/payment.ts
  src/core/api/options/bug.ts
  src/core/api/options/index.ts
  src/core/api/options/payment.ts
  src/core/mocks/datas/myCoupon.ts
  src/core/mocks/datas/productBugs.ts
  src/core/mocks/handlers/bugs.ts
  src/core/mocks/handlers/index.ts
  src/core/mocks/handlers/payment.ts
  src/core/routes/routes.tsx
  src/core/types/Confirm.ts
  src/core/types/MyCoupon.ts
  src/core/types/ProductBugs.ts
  src/core/types/PurchaseBugs.ts
  src/core/types/index.ts
  src/pages/PurchaseFailPage.tsx
  src/pages/PurchaseSuccesPage.tsx
  src/pages/StorePage.tsx
Labels: ☁️ FE, ✨ feature

#273 feat: 루틴 페이지 및 검색 페이지 피드백 반영
  src/RoomSlide/components/SlideController.tsx
  src/pages/RoutinesPage.tsx
  src/pages/SearchPage.tsx
Labels: ☁️ FE, ✨ feature

#275 feat: pc view 전용 UI 추가
  public/assets/typologo/typologo-dark.svg
  public/assets/typologo/typologo-light.svg
  src/AboutMoabam/components/AboutMoabam.tsx
  src/AboutMoabam/components/BirdButton.tsx
  src/AboutMoabam/components/IntroText.tsx
  src/AboutMoabam/components/Mark.tsx
  src/AboutMoabam/index.ts
  src/App.tsx
  src/main.css
Labels: ☁️ FE, ✨ feature

#277 feat: pc 뷰 전용 가이드 UI 추가
  public/assets/typologo/typologo-dark.svg
  public/assets/typologo/typologo-light.svg
  src/AboutMoabam/components/AboutMoabam.tsx
  src/AboutMoabam/components/BirdButton.tsx
  src/AboutMoabam/components/IntroText.tsx
  src/AboutMoabam/components/Mark.tsx
  src/AboutMoabam/index.ts
  src/App.tsx
  src/RoomDetail/components/RoomDetailContainer.tsx
  src/main.css
Labels: ☁️ FE, ✨ feature

#278 refactor: import-order 순서 정리
  .eslintrc.json
  src/App.tsx
  src/MyBird/components/BirdItems.tsx
  src/MyBird/components/ProductSheet.tsx
  src/PWAInstallBanner/components/PWAInstallBanner.tsx
  src/Promotion/components/EventCard.tsx
  src/RoomDetail/components/CertificationBottomSheet.tsx
  src/RoomDetail/components/CertificationProgress.tsx
  src/RoomDetail/components/ImageInput.tsx
  src/RoomDetail/components/ReportBottomSheet.tsx
  src/RoomDetail/components/RoomCalendarDate.tsx
  src/RoomDetail/components/RoomDetailContainer.tsx
  src/RoomDetail/components/RoomInfo.tsx
  src/RoomDetail/components/RoomMemberRank.tsx
  src/RoomDetail/components/RoomMembers.tsx
  src/RoomDetail/components/RoomRoutine.tsx
  src/RoomDetail/components/RoomWorkspace.tsx
  src/RoomForm/components/Password.tsx
  src/RoomForm/components/Routines.tsx
  src/RoomForm/components/UserCount.tsx
  src/RoomList/components/RoomAccordion.tsx
  src/RoomList/components/RoomCard.tsx
  src/RoomLog/components/RoomLogItem.tsx
  src/RoomNew/components/BirdCard.tsx
  src/RoomNew/components/Navbar.tsx
  src/RoomNew/hooks/useRoomForm.ts
  src/RoomNew/steps/PasswordStep.tsx
  src/RoomNew/steps/RoutineStep.tsx
  src/RoomNew/steps/SummaryStep.tsx
  src/RoomNew/steps/TimeStep.tsx
  src/RoomSearch/components/ResultList.tsx
  src/RoomSearch/components/SearchBar.tsx
  src/RoomSetting/hooks/useRoomForm.ts
  src/RoomSetting/tabs/MemberTab/DelegationButton.tsx
  src/RoomSetting/tabs/MemberTab/KickButton.tsx
  src/RoomSetting/tabs/MemberTab/index.tsx
  src/RoomSetting/tabs/RoomTab.tsx
  src/RoomSlide/components/NewRoomCard.tsx
  src/RoomSlide/components/RoomData.tsx
  src/RoomSlide/components/RoomSlide.tsx
  src/RoomSummary/components/RoomSummary.tsx
  src/StoreList/components/StoreList.tsx
  src/UserEtc/components/UserEtc.tsx
  src/UserProfile/components/UserMain.tsx
  src/core/api/functions/memberAPI.ts
  src/core/api/functions/roomAPI.ts
  src/core/routes/router.tsx
  src/pages/EventPage.tsx
  src/pages/MyBirdPage.tsx
  src/pages/Room.tsx
  src/pages/RoomDetailPage.tsx
  src/pages/RoomLogPage.tsx
  src/pages/SearchPage.tsx
  src/pages/StartPage.tsx
  src/pages/UserPage.tsx
  src/shared/Accordion/components/AccordionHeader.tsx
  src/shared/Header/Header.stories.tsx
  src/shared/Toast/components/ToastItem.tsx
Labels: ☁️ FE, ♻️ refactor

#280 refactor: 사용되지 않는 임시 코드 제거
  src/core/api/functions/examplePostAPI.ts
  src/core/api/options/examplePost.ts
  src/core/api/options/index.ts
  src/core/api/queries/.empty
  src/core/constants/.empty
  src/core/mocks/datas/comments.ts
  src/core/mocks/datas/posts.ts
  src/core/mocks/handlers/exampleComments.ts
  src/core/mocks/handlers/examplePosts.ts
  src/core/mocks/handlers/index.ts
  src/core/types/.empty
  src/core/utils/.empty
  src/pages/RoomDetailPage.tsx
Labels: ☁️ FE, ♻️ refactor

#283 feat: RoomSummary 컴포넌트 새 배경 색상 수정
  src/RoomSummary/components/RoomSummary.tsx
Labels: ☁️ FE, ✨ feature

#294 fix: 캘린더 일요일 관련 오류 수정
  src/RoomDetail/utils/makeWeekCalendar.ts
Labels: ☁️ FE, 🐛 fix

#288 feat: 오픈그래프 및 메타데이터 작성
  package-lock.json
  package.json
  public/assets/metaImage.png
  src/AboutMoabam/index.ts
  src/App.tsx
  src/Meta/components/CommonMeta.tsx
  src/Meta/components/RoomDetailMeta.tsx
  src/Meta/index.ts
  src/RoomDetail/components/RoomDetail.tsx
  src/RoomDetail/components/RoomSemi.tsx
  src/core/routes/routes.tsx
  src/main.tsx
Labels: ☁️ FE, ✨ feature

#285 refactor: 방 생성, 로그인 페이지 이미지 리팩토링
  public/assets/Omok.png
  public/assets/Owl.png
  src/RoomForm/constants/literals.ts
  src/RoomNew/components/BirdCard.tsx
  src/pages/JoinPage.tsx
Labels: ☁️ FE, ♻️ refactor

#291 fix: pc 전용 UI 에서 토스트가 이탈하는 버그 수정
  src/shared/Toast/components/ToastManager.tsx
Labels: ☁️ FE, 🐛 fix

#297 feat: 방 참여시 비밀번호 확인
  src/RoomDetail/components/RoomPreview.tsx
Labels: ☁️ FE

#299 fix: checkRoomJoin API에 대한 키 수정
  src/RoomDetail/components/RoomPreview.tsx
Labels: ☁️ FE, 🐛 fix

#301 fix: 오픈그래프 오류 수정 및 헤더 컴포넌트 수정
  src/Meta/components/CommonMeta.tsx
  src/Meta/components/RoomDetailMeta.tsx
  src/shared/Header/components/Header.tsx
Labels: ☁️ FE, ✨ feature, 🐛 fix

#302 fix: check room join API reload
  src/RoomDetail/components/RoomPreview.tsx
Labels: ☁️ FE, 🐛 fix

#304 fix: 방 참가 시 joinRoom API 요청
  src/RoomDetail/components/RoomPreview.tsx
  src/core/api/functions/roomAPI.ts
Labels: ☁️ FE, 🐛 fix

#307 fix: 방 상세페이지 기능들 수정
  src/RoomDetail/components/RoomDetail.tsx
  src/RoomDetail/components/RoomHeader.tsx
  src/RoomDetail/components/RoomMemberRank.tsx
  src/RoomDetail/components/RoomSemi.tsx
  src/pages/RoomDetailPage.tsx
Labels: ☁️ FE

#312 feat: 방장만 수정 버튼 보이기
  src/RoomDetail/components/RoomDetail.tsx
  src/RoomDetail/components/RoomHeader.tsx
Labels: ☁️ FE, 🐛 fix

#317 chore: MSW 경고 문구 출력에 필터 조건 추가
  src/main.tsx
Labels: ☁️ FE, 📦 chore

#319 feat: 이벤트 페이지 UI 수정 (발급 토스트)
  src/Promotion/components/EventCard.tsx
  src/Promotion/components/EventList.tsx
Labels: ☁️ FE, ✨ feature

#321 feat: opengraph 작성 수정
  index.html
  src/Meta/components/CommonMeta.tsx
  src/Meta/components/RoomDetailMeta.tsx
Labels: ☁️ FE, ✨ feature

#322 fix: opengraph og:url 수정
  index.html
Labels: ☁️ FE, 🐛 fix

#325 feat: input 에러메세지 추가
  src/RoomDetail/components/RoomDetail.tsx
  src/RoomDetail/components/RoomPreview.tsx
  src/RoomDetail/components/RoomSemi.tsx
  src/core/mocks/handlers/rooms.ts
  src/pages/RoomDetailPage.tsx
Labels: ☁️ FE, ✨ feature

#328 fix: 멤버 관련 로직 수정
  src/RoomDetail/components/RoomMembers.tsx
  src/shared/Avatar/Avatar.tsx
Labels: ☁️ FE, 🐛 fix

#329 refactor : 공지 UI 수정
  src/RoomDetail/components/RoomNotice.tsx
Labels: ☁️ FE

#331 fix: memberId 타입 number로 변경
  src/RoomDetail/components/ReportBottomSheet.tsx
  src/RoomDetail/components/RoomHeader.tsx
  src/RoomDetail/components/RoomMembers.tsx
  src/RoomDetail/components/RoomWorkspace.tsx
  src/RoomSetting/tabs/MemberTab/DelegationButton.tsx
  src/RoomSetting/tabs/MemberTab/KickButton.tsx
  src/RoomSetting/tabs/MemberTab/index.tsx
  src/core/api/functions/notificationAPI.ts
  src/core/api/functions/roomAPI.ts
  src/core/types/Member.ts
  src/core/types/Reports.ts
  src/shared/Avatar/Avatar.stories.ts
  src/shared/Avatar/Avatar.tsx
Labels: ☁️ FE, 🐛 fix

#335 fix: 방 상세 페이지 오류 수정
  src/RoomDetail/components/RoomHeader.tsx
  src/RoomDetail/components/RoomPreview.tsx
Labels: ☁️ FE, ✨ feature

#338 fix: 방 관리 페이지 접근 불가능한 오류
  src/RoomSetting/tabs/RoomTab.tsx
Labels: ☁️ FE, 🐛 fix

#337 feat: 마이, 상점 피드백 1차 적용
  src/MyBird/components/HeaderWallet.tsx
  src/MyBird/components/ProductSheet.tsx
  src/OrderLogList/components/OrderLogList.tsx
  src/UserProfile/components/UserMain.tsx
  src/UserProfile/components/UserProfile.tsx
  src/core/mocks/datas/bugHistory.ts
  src/core/mocks/datas/member.ts
  src/core/types/BugHistory.ts
  src/core/types/Member.ts
  src/pages/OrderLogPage.tsx
Labels: ☁️ FE

#340 fix: managerNickname 변수명 수정
  src/RoomDetail/components/RoomDetail.tsx
  src/RoomDetail/components/RoomHeader.tsx
  src/core/mocks/datas/room.ts
  src/core/types/Room.ts
Labels: ☁️ FE, 🐛 fix

#344 chore: 배포 env에 토스페이먼츠 추가
  .env.example
  .github/workflows/deploy.yml
Labels: ☁️ FE, 📦 chore

#347 fix: 방 관리 페이지 404 응답시 NotFound 렌더링
  src/RoomSetting/tabs/RoomTab.tsx
  src/pages/RoomNewPage.tsx
  src/pages/RoomSettingPage.tsx
Labels: ☁️ FE

#346 fix: 상세페이지 수정 1차
  src/RoomDetail/components/ReportBottomSheet.tsx
  src/RoomDetail/components/RoomMember.tsx
  src/RoomDetail/components/RoomMembers.tsx
  src/RoomDetail/components/RoomRoutine.tsx
  src/RoomDetail/components/RoomWorkspace.tsx
  src/RoomDetail/constants/constant.ts
  src/core/types/Reports.ts
  src/shared/Toast/components/ToastManager.tsx
Labels: ☁️ FE, 🐛 fix

#342 feat: 마이페이지 수정 2차
  src/OrderLogList/mocks/Bugs.ts
  src/OrderLogList/mocks/types/bugs.ts
  src/UserEtc/components/UserEtc.tsx
  src/UserProfile/components/UserMain.tsx
  src/core/mocks/datas/bugHistory.ts
  src/core/types/BugHistory.ts
Labels: ☁️ FE, ✨ feature

#355 fix: 이미지 인증을 위한 준비
  src/RoomDetail/components/CertificationBottomSheet.tsx
  src/RoomDetail/components/RoomMember.tsx
  src/RoomDetail/components/RoomRoutine.tsx
Labels: ☁️ FE, 🐛 fix

#353 feat: 방 수정 페이지 QA
  src/RoomSetting/hooks/useRoomForm.ts
  src/RoomSetting/tabs/MemberTab/DelegationButton.tsx
  src/RoomSetting/tabs/MemberTab/KickButton.tsx
  src/RoomSetting/tabs/MemberTab/index.tsx
  src/RoomSetting/tabs/RemoveTab.tsx
  src/core/api/functions/roomAPI.ts
  src/core/mocks/datas/room.ts
  src/core/mocks/handlers/rooms.ts
  src/core/types/Room.ts
  src/pages/RoomSettingPage.tsx
Labels: ☁️ FE, ♻️ refactor, ✨ feature

#354 feat: api 변경사항 반영
  src/LogList/components/LogList.tsx
  src/MyBird/components/ProductSheet.tsx
  src/MyCoupon/components/MyCouponList.tsx
  src/OrderLogList/components/OrderLogList.tsx
  src/core/api/functions/itemAPI.ts
Labels: ☁️ FE, ✨ feature

#356 feat: 전송 파일 형태 변경
  src/RoomDetail/components/CertificationBottomSheet.tsx
  src/core/mocks/handlers/rooms.ts
Labels: ☁️ FE, 🐛 fix

#357 fix: 전송 파일 형태 변경
  src/RoomDetail/components/CertificationBottomSheet.tsx
Labels: ☁️ FE, 🐛 fix

#358 fix: 사진 인증 타입 수정
  src/RoomDetail/components/CertificationBottomSheet.tsx
Labels: ☁️ FE, 🐛 fix

#359 fix: formdata 수정
  src/RoomDetail/components/CertificationBottomSheet.tsx
Labels: ☁️ FE, 🐛 fix

#348 feat: 시작페이지 fade in 추가
  src/pages/StartPage.tsx
Labels: ☁️ FE, ✨ feature

#363 fix: 시작페이지 데이터 중복 요청 현상 수정
  src/RoomSlide/components/RoomSlide.tsx
  src/RoomSlide/index.ts
  src/StartSlide/components/FakeRoutinesPage.tsx
  src/StartSlide/index.ts
  src/pages/StartPage.tsx
Labels: ☁️ FE, 🐛 fix
